name: Sync to Hugging Face

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # এখানে তোমার নতুন ইউজারনেম এবং রেপোর নাম আপডেট করা হয়েছে
          git push --force https://Madarauchihagmailcom:$HF_TOKEN@huggingface.co/spaces/Madarauchihagmailcom/MyMail main